### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by alinaimi**
covering more extensions

### CODE REVIEW

**Review by arnonrdp — APPROVED** [review]

**Comment by mfloto** [comment]
Apparently `.sl3` is also an associated extension.

**Review by mfloto — APPROVED** [review]

**Review by judemont — APPROVED** [review]

**Comment by turbotimon** [comment]
@judemont Is there something preventing this merge? I like the simplicity and clean UI of this extension. However my sqlite DBs have also often a .db ending for compatibility with other tools. So I really would like to have this option.

If merge is ok, the README should be updated accordingly.

As other databases than sqlite sometimes also use `.db` ending, we could check the [Magic Header String (see 1.3.1)](https://www.sqlite.org/fileformat.html) of a .db file (or in general for all files): *"SQLite format 3\000"*

**Comment by judemont** [comment]
I don't know, I approved this pull request because I'd also like to be able to open .db files but I'm not a contributor to this project and I don't work on it. 😊

**Comment by judemont** [comment]
> @judemont @alinaimi Is there something preventing this merge? I like the simplicity and clean UI of this extension. However my sqlite DBs have also often a `.db` ending for compatibility with other tools. So I really would like to have this option.
> 
> If merge is ok, the README should be updated accordingly.
> 
> As other databases than sqlite sometimes also use `.db` ending, we could check the [Magic Header String (see 1.3.1)](https://www.sqlite.org/fileformat.html) of a .db file (or in general for all files): *"SQLite format 3\000"*

I don't know, I approved this pull request because I'd also like to be able to open .db files but I'm not a contributor to this project and I don't work on it. 😊

**Pull request closed without merging**
